name: cosmic-saga # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Cosmic Warlords Saga
summary: Battle for power across the galaxy.
description: Build your fleet, command your army, and defeat rival extraterrestrial warlords to claim galactic dominance.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  cosmic-saga:
    command: bin/cosmic-saga-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  cosmic-saga:
    plugin: dump
    source: .
    organize:
      cosmic-saga-bin: bin/
